<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <RootNamespace>KinectV2Server</RootNamespace>
    <AssemblyName>KinectV2Server</AssemblyName>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <UseWindowsForms>true</UseWindowsForms>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.Drawing.Common" Version="9.0.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\ProCamCalibration\ProCamEnsembleCalibration\ProCamEnsembleCalibrationLib.csproj" />
    <ProjectReference Include="..\ConsoleTextBox\ConsoleTextBox.csproj" />
  </ItemGroup>
</Project>
