syntax = "proto3";

package roomalive;

option csharp_namespace = "RoomAlive.Grpc";

import "google/protobuf/empty.proto";

service KinectServer2 {
  rpc LatestDepthImage (google.protobuf.Empty) returns (ImageReply);
  rpc LatestYUVImage (google.protobuf.Empty) returns (ImageReply);
  rpc LatestRGBImage (google.protobuf.Empty) returns (ImageReply);
  rpc LatestJPEGImage (google.protobuf.Empty) returns (ImageReply);
  rpc LastColorGain (google.protobuf.Empty) returns (ColorGainReply);
  rpc LastColorExposureTimeTicks (google.protobuf.Empty) returns (ExposureTimeTicksReply);
  rpc GetCalibration (google.protobuf.Empty) returns (Kinect2CalibrationData);
}

message ImageReply {
  bytes data = 1;
}

message ColorGainReply {
  float gain = 1;
}

message ExposureTimeTicksReply {
  int64 ticks = 1;
}

message Kinect2CalibrationData {
  bytes color_camera_matrix = 1;
  bytes color_lens_distortion = 2;
  bytes depth_camera_matrix = 3;
  bytes depth_lens_distortion = 4;
  bytes depth_to_color_transform = 5;
}
