<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <RootNamespace>KinectServer2Console</RootNamespace>
    <AssemblyName>KinectServer</AssemblyName>
    <UseWindowsForms>true</UseWindowsForms>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>


  <ItemGroup>
    <ProjectReference Include="..\ProCamEnsembleCalibration\ProCamEnsembleCalibrationLib.csproj" />
  </ItemGroup>

</Project>
